voice_group emerald_universal
    voice_keysplit_all voicegroup_frlg_drumset                                                                  @ 0 FRLG drumset
    voice_keysplit voicegroup_piano_keysplit, keysplit_piano                                                    @ 1 piano
    voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 165, 103, 235                           @ 2 piano 2
    voice_square_2_alt 60, 0, 2, 1, 4, 4, 2                                                                     @ 3 PSG sq2 (littleroot)
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 188, 128, 226             @ 4 electric piano [low]
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 204, 77, 246             @ 5 electric piano [high]
    voice_square_2 60, 0, 2, 0, 0, 9, 2                                                                         @ 6 PSG sq2 (dummy voicegroup)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127                          @ 8 square wave [directsound]
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242                        @ 9 glockenspiel
    voice_directsound 60, 0, DirectSoundWaveData_heart_of_asia_gamelan, 255, 188, 139, 239                      @ 10 gamelan
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204                            @ 13 xylophone
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216                        @ 14 bell
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 76, 133, 137                              @ 17 percussive organ
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 128, 160, 175, 165                             @ 18 percussive organ [soft]
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188                   @ 19 church organ low
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188                  @ 20 church organ high
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165                            @ 21 accordion
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 64, 188, 108, 165                           @ 21 accordion [soft]
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 76                     @ 24 nylon string guitar
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 64, 216, 51, 224                     @ 25 nylon string guitar [soft]
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_15, 0, 7, 15, 0                                     @ 27 PSG wv15 (rg_vs_deoxys)
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_16, 0, 7, 15, 0                                     @ 27 PSG wv16 (rg_vs_deoxys)
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127              @ 29 overdrive guitar
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127        @ 30 distortion guitar high
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 127         @ 31 distortion guitar low
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149                        @ 33 fingered bass
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 64, 204, 113, 235                       @ 34 fingered bass [soft]
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 188                        @ 35 fretless bass
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 99                           @ 36 slap bass
    voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216                 @ 37 unison slap
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115                           @ 38 synth bass
    voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 178, 180, 165                    @ 39 synth bass 2
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165                    @ 45 pizzicato strings
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 246, 0, 235                                 @ 46 harp
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 165, 154, 153                            @ 47 timpani
    voice_keysplit voicegroup_strings_keysplit, keysplit_strings                                                @ 48 string ensemble
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 165, 154, 127                          @ 50 synth strings
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0                     @ 52 choir
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204                       @ 54 synth voice
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet                                                @ 56 trumpet
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_keysplit voicegroup_tuba_keysplit, keysplit_tuba                                                      @ 58 tuba
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_keysplit voicegroup_french_horn_keysplit, keysplit_french_horn                                        @ 60 french horn
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165                         @ 68 oboe
    voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165                            @ 69 oboe 2
    voice_square_1 60, 0, 0, 2, 0, 7, 0, 6                                                                      @ 70 PSG sq1 (rg_pallet)
    voice_square_2_alt 60, 0, 1, 1, 5, 1, 6                                                                     @ 71 PSG sq2 (rg_pallet)
    voice_square_1 60, 0, 0, 0, 1, 4, 3, 6                                                                      @ 72 PSG sq1 (rg_pallet)
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127                              @ 73 flute
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 1                                      @ 74 PSG wv1 (victory_wild)
    voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165                   @ 75 shakuhachi [enhanced delay]
    voice_square_2_alt 60, 0, 3, 0, 4, 4, 4                                                                     @ 76 PSG sq2 (rg_vs_trainer)
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 191, 97, 165                   @ 77 shakuhachi
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127                       @ 78 whistle
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 85, 204, 77, 127                       @ 79 whistle [soft]
    voice_square_1 60, 0, 0, 2, 0, 1, 7, 1                                                                      @ 80 PSG sq1 (fanfare)
    voice_square_2_alt 60, 0, 2, 0, 1, 7, 1                                                                     @ 81 PSG sq2 (fanfare)
    voice_square_1 60, 0, 0, 3, 0, 1, 7, 1                                                                      @ 82 PSG sq1 (victory_gym_leader)
    voice_square_2_alt 60, 0, 3, 0, 1, 7, 1                                                                     @ 83 PSG sq2 (victory_gym_leader)
    voice_square_1 60, 0, 0, 0, 0, 1, 7, 1                                                                      @ 84 PSG sq1 (vs_champion)
    voice_square_2 60, 0, 0, 0, 1, 7, 1                                                                         @ 85 PSG sq2 (vs_champion)
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 1                                      @ 86 PSG wv6 (victory_gym_leader)
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 7, 15, 0                                      @ 87 PSG wv5 (rg_vs_trainer)
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_2, 0, 7, 15, 0                                      @ 88 PSG wv2 (rg_vs_trainer)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_8, 0, 1, 12, 0                                      @ 92 PSG wv8 (rg_route11)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 1, 1, 1                                                                      @ 100 PSG sq1 (vs_wild)
    voice_square_2 60, 0, 2, 0, 1, 1, 1                                                                         @ 101 PSG sq2 (vs_wild)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 165, 206, 127        @ 104 power chord
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242                            @ 106 koto [high]
    voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242                             @ 107 koto [low]
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231         @ 112 ride bell (percussion)
    voice_directsound_no_resample 64, 89, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 242                    @ 113 cowbell (percussion)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0                                 @ 116 taiko (percussion)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound_no_resample 60, 0, DirectSoundWaveData_sc88pro_timpani_with_snare, 255, 246, 0, 226       @ 118 timpani + snare
    voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216    @ 119 reverse cymbal (percussion)
    voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 165                    @ 120 scream drive
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 127                              @ 122 bubbles (sfx)
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_noise_alt 60, 0, 0, 0, 1, 0, 0                                                                        @ 125 PSG noise (slateport)
    voice_noise_alt 60, 0, 0, 0, 2, 6, 0                                                                        @ 126 GB noise (rg_vs_wild)
    voice_noise_alt 60, 0, 0, 0, 1, 6, 1                                                                        @ 127 GB noise (rg_vs_wild)
