gText_WantToSurfWithPokemon:
    .string "水面呈现出一片湛蓝。\n"
    .string "要{STR_VAR_1}使用冲浪吗？$"

gText_MonHelpedSurf:
    .string "{STR_VAR_1}使出了冲浪！$"

gText_WantToSurfWithItem:
    .string "水面呈现出一片湛蓝。\n"
    .string "要使用{STR_VAR_2}吗？$"

gText_PlayerUsedSurfItem:
    .string "你使出了{STR_VAR_2}的冲浪功能！$"
    
gText_CantSurf:
	.string "水面呈现出一片湛蓝。"

@ will likely delete the below
gText_WantToUseSurf::
	.string "水面呈现出一片湛蓝。\n要使用冲浪吗？$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1}使出了冲浪！$"

Text_CurrentTooFast::
	.string "水流实在太湍急了！\n这里无法使用冲浪……$"
